src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use App\Service\PropertyHeatHelper;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\String\Slugger\AsciiSlugger;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @UniqueEntity("title")
 * @Vich\Uploadable
 */
class Property
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="string")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean")
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity=Specification::class, inversedBy="properties")
     */
    private $specifications;

    /**
     * @ORM\OneToMany(targetEntity=Picture::class, mappedBy="property", orphanRemoval=true, cascade={"persist"})
     */
    private $pictures;

    /**
     * @var
     */
    private $pictureFiles;

    /**
     * @ORM\Column(type="float", scale=4, precision=6)
     */
    private $lat;

    /**
     * @ORM\Column(type="float", scale=4, precision=7)
     */
    private $lng;
    
    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->specifications = new ArrayCollection();
        $this->pictures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (string)(new AsciiSlugger())->slug($this->getTitle())->lower();
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getHeat(): ?string
    {
        return $this->heat;
    }

    public function setHeat(string $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatLabel(): string
    {
        return PropertyHeatHelper::getLabel($this->getHeat());
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Specification[]
     */
    public function getSpecifications(): Collection
    {
        return $this->specifications;
    }

    public function addSpecification(Specification $specification): self
    {
        if (!$this->specifications->contains($specification)) {
            $this->specifications[] = $specification;
            $specification->addProperty($this);
        }

        return $this;
    }

    public function removeSpecification(Specification $specification): self
    {
        if ($this->specifications->removeElement($specification)) {
            $specification->removeProperty($this);
        }

        return $this;
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function getPicture(): ?Picture
    {
        if ($this->pictures->isEmpty()) {
            return null;
        }
        return $this->pictures->first();
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setProperty($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getProperty() === $this) {
                $picture->setProperty(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPictureFiles()
    {
        return $this->pictureFiles;
    }

    /**
     * @param mixed $pictureFiles
     * @return Property
     */
    public function setPictureFiles($pictureFiles): self
    {
        foreach ($pictureFiles as $pictureFile) {
            $picture = new Picture();
            $picture->setImageFile($pictureFile);
            $this->addPicture($picture);
        }
        $this->pictureFiles = $pictureFiles;
        return $this;
    }

    public function getLat(): ?float
    {
        return $this->lat;
    }

    public function setLat(float $lat): self
    {
        $this->lat = $lat;

        return $this;
    }

    public function getLng(): ?float
    {
        return $this->lng;
    }

    public function setLng(float $lng): self
    {
        $this->lng = $lng;

        return $this;
    }

}

src/Controller/Admin/AdminPropertyController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Property;
use App\Form\PropertyType;
use App\Repository\PropertyRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/property")
 */
class AdminPropertyController extends AbstractController
{
    /**
     * @Route("/", name="ADMIN_PROPERTY_INDEX", methods={"GET"})
     */
    public function index(PropertyRepository $propertyRepository): Response
    {
        return $this->render('admin/property/index.html.twig', [
            'properties' => $propertyRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="ADMIN_PROPERTY_NEW", methods={"GET","POST"})
     */
    public function new(Request $request, ManagerRegistry $doctrine): Response
    {
        $property = new Property();
        $form = $this->createForm(PropertyType::class, $property);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $doctrine->getManager();
            $entityManager->persist($property);
            $entityManager->flush();

            $this->addFlash('success', 'La propriété a bien été créée');

            return $this->redirectToRoute('ADMIN_PROPERTY_INDEX', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin/property/new.html.twig', [
            'property' => $property,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="ADMIN_PROPERTY_SHOW", methods={"GET"})
     */
    public function show(Property $property): Response
    {
        return $this->render('admin/property/show.html.twig', [
            'property' => $property,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="ADMIN_PROPERTY_EDIT", methods={"GET","POST"})
     */
    public function edit(Request $request, Property $property, ManagerRegistry $doctrine): Response
    {
        $form = $this->createForm(PropertyType::class, $property);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $doctrine->getManager()->flush();

            $this->addFlash('success', 'La propriété a bien été modifiée');

            return $this->redirectToRoute('ADMIN_PROPERTY_INDEX', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin/property/edit.html.twig', [
            'property' => $property,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="ADMIN_PROPERTY_DELETE", methods={"POST"})
     */
    public function delete(Request $request, Property $property, ManagerRegistry $doctrine): Response
    {
        if ($this->isCsrfTokenValid('delete'.$property->getId(), $request->request->get('_token'))) {
            $entityManager = $doctrine->getManager();
            $entityManager->remove($property);
            $entityManager->flush();
        }

        $this->addFlash('success', 'La propriété a bien été supprimée');

        return $this->redirectToRoute('ADMIN_PROPERTY_INDEX', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/AdminPropertyController.php
<?php

namespace App\Controller;

use App\Entity\Property;
use App\Form\PropertyType;
use App\Repository\PropertyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin")
 */
class AdminPropertyController extends AbstractController
{
    /**
     * @Route("/", name="ADMIN_PROPERTY_INDEX", methods={"GET"})
     */
    public function index(PropertyRepository $propertyRepository): Response
    {
        return $this->render('admin_property/index.html.twig', [
            'properties' => $propertyRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="ADMIN_PROPERTY_NEW", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $property = new Property();
        $form = $this->createForm(PropertyType::class, $property);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($property);
            $entityManager->flush();

            return $this->redirectToRoute('ADMIN_PROPERTY_INDEX', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_property/new.html.twig', [
            'property' => $property,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="ADMIN_PROPERTY_SHOW", methods={"GET"})
     */
    public function show(Property $property): Response
    {
        return $this->render('admin_property/show.html.twig', [
            'property' => $property,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="ADMIN_PROPERTY_EDIT", methods={"GET","POST"})
     */
    public function edit(Request $request, Property $property): Response
    {
        $form = $this->createForm(PropertyType::class, $property);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('ADMIN_PROPERTY_INDEX', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_property/edit.html.twig', [
            'property' => $property,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="ADMIN_PROPERTY_DELETE", methods={"POST"})
     */
    public function delete(Request $request, Property $property): Response
    {
        if ($this->isCsrfTokenValid('delete'.$property->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($property);
            $entityManager->flush();
        }

        return $this->redirectToRoute('ADMIN_PROPERTY_INDEX', [], Response::HTTP_SEE_OTHER);
    }
}

templates/admin_property/_form.html.twig
{{ form_start(form) }}
    <div class="col-md-6">{{ form_row(form.title) }}</div>
    <div class="col-md-6">{{ form_row(form.description) }}</div>
    <div class="row">
        <div class="col-md-2">{{ form_row(form.surface) }}</div>
        <div class="col-md-2">{{ form_row(form.rooms) }}</div>
        <div class="col-md-2">{{ form_row(form.bedrooms) }}</div>
    </div>
    <div class="row">
        <div class="col-md-2">{{ form_row(form.floor) }}</div>
        <div class="col-md-2">{{ form_row(form.heat) }}</div>
    </div>
    <div class="row">
        <div class="col-md-2">{{ form_row(form.address) }}</div>
        <div class="col-md-2">{{ form_row(form.city) }}</div>
        <div class="col-md-2">{{ form_row(form.postal_code) }}</div>
    </div>
    <div class="row">
        <div class="col-md-4">{{ form_row(form.price) }}</div>
        <div class="col-md-4 d-flex align-items-center">{{ form_row(form.sold) }}</div>
    </div>
    <p><button class="btn btn-success btn-sm">Valider</button></p>
{{ form_end(form) }}

templates/admin_property/index.html.twig
{% extends 'base-admin.html.twig' %}

{% block title %}{% endblock %}

{% block body %}

    <div class="container">
        <section class="my-5">

            <h1>Tableau de bord</h1>

            <hr class="my-4">

            <p class="my-4"><a href="{{ path('ADMIN_PROPERTY_NEW') }}" class="btn btn-primary btn-sm">Créer un nouveau bien</a></p>

            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Titre</th>
                    <th>Description</th>
                    <th>Surface</th>
                    <th>Pièces</th>
                    <th>Chambres</th>
                    <th>Étages</th>
                    <th>Prix</th>
                    <th>Chauffage</th>
                    <th>Adresse</th>
                    <th>Vendu</th>
                    <th>Ajouté le</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for property in properties %}
                    <tr>
                        <td>{{ property.title }}</td>
                        <td>{{ property.description }}</td>
                        <td>{{ property.surface }} m²</td>
                        <td>{{ property.rooms }}</td>
                        <td>{{ property.bedrooms }}</td>
                        <td>{{ property.floor }}</td>
                        <td>{{ property.formattedPrice }}</td>
                        <td>{{ property.heatLabel }}</td>
                        <td>
                            {{ property.address }}<br>
                            {{ property.postalCode }} {{ property.city }}
                        </td>
                        <td>
                            {{ property.sold ? 'OUI' : 'NON' }}
                        </td>
                        <td>{{ property.createdAt ? property.createdAt|date('d-m-Y') }}</td>
                        <td>
                            <a href="{{ path('ADMIN_PROPERTY_SHOW', {'id': property.id}) }}" class="btn btn-primary btn-sm">Voir</a><br>
                            <a href="{{ path('ADMIN_PROPERTY_EDIT', {'id': property.id}) }}" class="btn btn-primary btn-sm my-1">Modifier</a><br>
                            {{ include('admin_property/_delete_form.html.twig') }}
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="15">Aucun bien enregistré</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </section>
    </div>

{% endblock %}

templates/admin_property/new.html.twig
{% extends 'base-admin.html.twig' %}

{% block title %} - Nouveau bien{% endblock %}

{% block body %}

    <div class="container">
        <section class="my-5">

            <h1>Créer un nouveau bien</h1>

            <hr class="my-4">

            <p class="my-4"><a href="{{ path('ADMIN_PROPERTY_INDEX') }}" class="btn btn-primary btn-sm">Retour à la liste</a></p>

            {{ include('admin_property/_form.html.twig') }}

        </section>
    </div>

{% endblock %}

templates/admin_property/show.html.twig
{% extends 'base-admin.html.twig' %}

{% block title %} - {{ property.title }}{% endblock %}

{% block body %}

    <div class="container">
        <section class="my-5">

            <h1>{{ property.title }}</h1>

            <hr class="my-4">

            <p class="my-4"><a href="{{ path('ADMIN_PROPERTY_INDEX') }}" class="btn btn-primary btn-sm">Retour à la liste</a></p>

            <table class="table table-striped">
                <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ property.id }}</td>
                </tr>
                <tr>
                    <th>Titre</th>
                    <td>{{ property.title }}</td>
                </tr>
                <tr>
                    <th>Description</th>
                    <td>{{ property.description }}</td>
                </tr>
                <tr>
                    <th>Surface</th>
                    <td>{{ property.surface }} m²</td>
                </tr>
                <tr>
                    <th>Pièces</th>
                    <td>{{ property.rooms }}</td>
                </tr>
                <tr>
                    <th>Chambres</th>
                    <td>{{ property.bedrooms }}</td>
                </tr>
                <tr>
                    <th>Étages</th>
                    <td>{{ property.floor }} </td>
                </tr>
                <tr>
                    <th>Prix</th>
                    <td>{{ property.formattedPrice }}</td>
                </tr>
                <tr>
                    <th>Chauffage</th>
                    <td>{{ property.heat }}</td>
                </tr>
                <tr>
                    <th>Adresse</th>
                    <td>{{ property.address }}, {{ property.postalCode }} {{ property.city }}</td>
                </tr>
                <tr>
                    <th>Vendu</th>
                    <td>{{ property.sold ? 'OUI' : 'NON' }}</td>
                </tr>
                <tr>
                    <th>Date de création</th>
                    <td>{{ property.createdAt ? property.createdAt|date('d-m-Y') }}</td>
                </tr>
                </tbody>
            </table>

            <p><a href="{{ path('ADMIN_PROPERTY_EDIT', {'id': property.id}) }}" class="btn btn-primary btn-sm">Modifier</a></p>

            {{ include('admin_property/_delete_form.html.twig') }}
        </section>
    </div>

{% endblock %}